sudo: true

language: bash

services:
  - docker

env:
  - DEBIAN_FRONTEND=noninteractive

jobs:
  include:
    - stage: SetupHost
      script:
        - /bin/bash pre_install
    - stage: BuildMasterdev
      if: (branch = master) AND (NOT (type IN (pull_request))) AND (tag IS blank)
      script:
        - docker --version
        - docker manifest
