sudo: true

language: bash

services:
  - docker

env:
  - DEBIAN_FRONTEND=noninteractive

jobs:
  include:
    - stage: Check
      before_install:
        - ./pre_install
      script:
        - docker --version
        - docker manifest
